-- create Income Statements table
CREATE TABLE income_statement (
                                  id VARCHAR PRIMARY KEY NOT NULL ,
                                  ticker VARCHAR(10) NOT NULL ,
                                  type VARCHAR(10) NOT NULL,
                                  fiscaldateending DATE NOT NULL ,
                                  reportedcurrency VARCHAR(10) NOT NULL ,
                                  grossprofit BIGINT,
                                  totalrevenue BIGINT,
                                  costofrevenue BIGINT,
                                  costofgoodsandservicessold BIGINT,
                                  operatingincome BIGINT,
                                  sellinggeneralandadministrative BIGINT,
                                  researchanddevelopment BIGINT,
                                  operatingexpenses BIGINT,
                                  investmentincomenet BIGINT,
                                  netinterestincome BIGINT,
                                  interestincome BIGINT,
                                  interestexpense BIGINT,
                                  noninterestincome BIGINT,
                                  othernonoperatingincome BIGINT,
                                  depreciation BIGINT,
                                  depreciationandamortization BIGINT,
                                  incomebeforetax BIGINT,
                                  incometaxexpense BIGINT,
                                  interestanddebtexpense BIGINT,
                                  netincomefromcontinuingoperations BIGINT,
                                  comprehensiveincomenetoftax BIGINT,
                                  ebit BIGINT,
                                  ebitda BIGINT,
                                  netincome BIGINT
);